ZTC/Controllers/EntradaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ZTC.Bll;
using ZTC.Model;
using ZTC.Models;
using ZTC.Models.ENUMS;
using System.Net.Mail;
namespace ZTC.Controllers
{
    public class EntradaController : BaseController
    {
        // GET: Entrada
        [AccessDeniedAuthorize]
        public ActionResult Index()
        {
            var entrada = new List<Entrada>();
            var bll = new EntradaBll();

            string sql = "";

            entrada = bll.GetList(sql, true);

            return View(entrada);
        }

        // GET: Entrada/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Entrada/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Entrada/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Entrada/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Entrada/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Entrada/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Entrada/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ZTC/Views/Entrada/Create.cshtml
@model ZTC.Model.Entrada

@{
    ViewBag.Title = "Criar Novo Mensalista";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    #tableUsuario tr td {
        padding: 5px 5px 5px 5px;
    }

    .drop-down {
        height: 20px;
    }

    .error {
        color: #a94442;
    }
</style>



<h2>Criar Nova Entrada</h2>
<div class="content">

    <form action="@Url.Action("Create", "Entrada")" method="POST" name="form1">
        <input type="hidden" name="idMensalista" id="idMensalista" />
        <input type="hidden" name="idAvulso" id="idAvulso" />
        <table class="tablespc" style="margin-bottom: 10px">

            <tr>
                <td width="130px">
                    <span>Placa</span>
                </td>
                <td colspan="5">
                    <input type="text" name="placa" id="placa" class="input-pdr" style="width: 560px;" required="required" />
                    <button id="btnBuscarPorNomeEmpresa" class="btnPesquisar tooltipicon" data-title="Pesquisar"><span class="glyphicon glyphicon-search"></span></button>
                    <button type="button" name="limparCampos1" id="limparCampos1" value="Limpar" onclick="limparCampos()" title="Limpar Dados Empresa" alt="Limpar Dados Empresa" class="btn btn-sm btn-row glyphicon glyphicon-remove hide"></button>
                </td>
            </tr>
            <tr>
                <td>Carro</td>
                <td>
                    <input type="text" id="carro" name="carro" class="input-pdr" style="width: 173px" required="required" />
                </td>
                <td>Nome Cliente</td>
                <td>
                    <input type="text" id="nomeCliente" name="nomeCliente" class="input-pdr" style="width: 220px" />
                </td>


            </tr>


            <tr>
                <td>Data Hora Entrada</td>
                <td colspan="1">
                    <input type="text" id="dataHoraEntrada" name="dataHoraEntrada" class="input-pdr datetimepicker" style="width: 173px" required="required" />
                </td>
                <td>Serviço:</td>
                <td style="position: relative;">
                    <select name="servico" id="servico" style="width: 220px">
                        <option>-</option>
                        <option name="servico" value="Estacionamento">Estacionamento</option>
                        <option name="servico" value="Lavagem">Lavagem</option>
                        <option name="servico" value="Outros">Outros</option>
                    </select>
                </td>

            </tr>

            <tr>
                <td>Fechado:</td>
                <td width="166px">
                    @Html.EditorFor(model => model.Fechado)
                    @Html.ValidationMessageFor(model => model.Fechado, "", new { @class = "text-danger" })
                </td>
            </tr>

            <tr>
                <td colspan="6">
                    <input type="submit" value="Salvar" id="btnSalvar" class="btn btnGreen" style="width: 85px; height: 34px; margin-left: 130px;" />
                    <a href='@Url.Action("/", "Entrada")'>
                        <input type="button" class="btn btnWhite dropdown-toggle" value="Cancelar" style="width: 85px; height: 34px;" />
                    </a>
                </td>
            </tr>


        </table>
    </form>


</div>
<div id="popUpEmpresas" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content" style="width: 600px;">
            <div class="modal-header" style="border-bottom: 1px solid #ffffff;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div id="listEmpresas">

            </div>

        </div>

    </div>
</div>


<script>

     $(function ($) {
         $("#placa").mask("aaa-9999");
         

     });

</script>
<script>
     $("#btnBuscarPorNomeEmpresa").click(function () {
         CarregarEmpresaNomeEmpresa();
     });

     function CarregarEmpresaNomeEmpresa() {
         event.preventDefault();
         var item = $("#placa").val();


         $.ajax({
             url: "/api/ClientesApi/GetByNomeMensalista?placa=" + item,
             type: "GET",
             dataType: "JSON",
             success: function (arr) {
                 var table = "";
                 table += '<table class="table table-hover">';

                 table += '<tr class="active">';
                 table += '<td style="text-align: center;">Nome Cliente</td>';
                 table += '<td style="text-align: center;">Carro</td>';
                 table += '<td style="text-align: center;">Placa</td>';
                 table += '<td style="text-align: center;">Selecione</td>';
                 table += '</tr>';

                 jQuery.each(arr, function (index, valor) {
                     //$("#placa").val(valor._placa);
                     //$("#nomeRepresentanteLegal").val(valor._idPessoaRepresentante._nome);
                     //$("#campocnpj").val(valor._cNPJ);
                     //console.log(valor);


                     table += '<tr>';
                     table += '<td style="text-align: center;">' + valor._nome + '</td>';
                     table += '<td style="text-align: center;">' + valor._carro + '</td>';
                     table += '<td style="text-align: center;">' + valor._placa + '</td>';
                     table += '<td style="text-align: center; cursor:pointer;"><a onclick="buscarCnpj(\'' + valor._nome + '\')">Selecionar</a></td>';
                     table += '</tr>';


                 });
                 table += "</table>";

                 $("#listEmpresas").empty().append(table);

                 $('#popUpEmpresas').modal('show');

                 //if (valor._idEmpresa > 0);

                 //else
                 //    jAlert('Não existe empresas', 'Info');
             },
             error: function (valor) {
                 $("#nomeRepresentanteLegal").val("");
                 $("#campocnpj").val("");
                 $("#fone").val("");
             }


         });


     }

     $("#btnBuscarPorCnpj").click(function () {
         CarregarEmpresaCnpj();
     });

     function buscarCnpj(nome) {
         $("#nomeCliente").val(nome);
         CarregarEmpresaCnpj();
         bloquearCampos();

         console.log(nome);
     }

     function CarregarEmpresaCnpj() {
         var item = $("#nomeCliente").val();


         $.ajax({
             url: "/api/ClientesApi/GetByNomeCliente?nomeCliente=" + item,
             type: "GET",
             dataType: "JSON",
             success: function (valor) {

                 $("#placa").val(valor._placa);
                 $("#carro").val(valor._carro);

                 console.log(valor._nome);
                 console.log(valor);
                 if (valor._idMensalista > 0)
                     bloquearCampos();
                 else
                     jAlert('PLACA não cadastrada', 'Info');
             },
             error: function (valor) {
                 $("#placa").val("");
                 $("#nomeCliente").val("");
             }
         });


     }

     function bloquearCampos(parameters) {
         $("#popUpEmpresas").modal("hide");
         $("#popUpRepresentante").modal("hide");
         $("#popUpCnpj").modal("hide");
         $("#nomeCliente").attr("disabled", false);
         $("#carro").attr("disabled", false);
         $("#placa").attr("disabled", false);
         $("#limparCampos1").removeClass("hide");
     }

     function limparCampos() {

         $("#limparCampos1").addClass("hide");
         document.getElementById('nomeCliente').value = "";
         document.getElementById('nomeCliente').disabled = false;
         document.getElementById('carro').value = "";
         document.getElementById('carro').disabled = false;
         document.getElementById('placa').value = "";
         document.getElementById('placa').disabled = false;
     }




</script>

ZTC/Views/Entrada/Index.cshtml
@model List<ZTC.Model.Entrada>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Index";
}
<style>
    .table tr td, th {
        font-size: 11px;
    }

    .datetimepicker {
        z-index: 100000;
    }

    .espacamentoTd {
        padding: 3px;
    }

    .dropdown-new {
        font-size: 11px;
        max-height: 28px;
    }

    .bs-example {
        margin: 20px;
    }

    .icon-input-btn {
        display: inline-block;
        position: relative;
    }

        .icon-input-btn input[type="submit"] {
            padding-left: 2em;
        }

        .icon-input-btn .glyphicon {
            display: inline-block;
            position: absolute;
            left: 0.65em;
            top: 30%;
        }
</style>

<style>
    div.funil {
        width: 350px;
        /*height: 126px;
            border-top: 3px solid #c90000;
            background-color: #fff;
            box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.2);*/
    }

        div.funil input {
            width: 164px;
            /*margin: 6px 0 6px 6px;*/
        }

        div.funil hr {
            border: 0px;
            height: 1px;
            margin: 0px;
            background: #E5E5E5;
        }

        div.funil table {
            font-size: 11pt;
        }

        div.funil div.botDown {
            /*background: #f9e5e5;
                color: #c90000;
                border-top: 2px solid #c90000;*/
            height: 64px;
            font-size: 22pt;
            text-align: center;
            cursor: pointer;
        }

    .tableFiltro td.tdFiltro {
        /*padding: 10px;*/
    }

    div.overlay {
        z-index: 50;
        /*background: rgba(255,255,255,0.7);
            position: absolute;
            width: 350px;
            height: 126px;*/
    }

    div.funil .overlay > .fa, .overlay-wrapper .overlay > .fa {
        position: absolute;
        margin-left: 50px;
        /*margin-top: 52px;*/
        color: #000;
        font-size: 30px;
        z-index: 9999;
        opacity: 1;
    }

    .opacity-overlay {
        opacity: 0.3;
    }

    .fa-spin {
    }
</style>


<h2>Entrada</h2>




<div class="content" style="padding: 10px; width: 1120px">
    <input type="button" name="button" class="btn btnGreen" value="Adicionar Entrada" onclick='javascript: location.href = "@Url.Action("Create", "Entrada")"' />
    <br /><br />
    <table class="table table-striped">
        <tr>
            <th style="text-align:center">
                Nome
            </th>
            <th style="text-align:center">
                Placa
            </th>
            <th style="text-align:center">
                Carro
            </th>
            <th style="text-align:center">
                Servico
            </th>
            <th style="text-align:center">
                Data Entrada
            </th>
            <th style="text-align:center">
                Fechado
            </th>
           <th style="text-align:center">Ações</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Placa)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Carro)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Servico)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.DataHoraEntrada)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Fechado)
                </td>
                <td style="text-align:center">
                        <a href="@Url.Action("Edit", "Entrada", new { id = item.IdEntrada })" class="btn btn-xs btn-pen tooltipicon" data-title="Editar"><span class="glyphicon glyphicon-pencil"></span></a>
            </tr>
        }
    </table>

</div>

<script>
    $(".tooltipicon").ggtooltip({ textcolor: "#FFF", backcolor: "#3C3C3C", bordercolor: "#3C3C3C", placement: "top" });
</script>