ZTC/Models/Avulso.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using ZTC.Models.ENUMS;

namespace ZTC.Model
{
    [Serializable]
    public class Avulso
    {
        #region Atributos
        private int _idAvulso;
        private string _nome;
        private string _cpf;
        private string _telefoneFixo;
        private string _telefoneCelular;
        private string _marca;
        private string _carro;
        private string _placa;
        private string _cor;
        private string _obs;
        #endregion

        #region Propriedades

        public int IdAvulso
        {
            get { return _idAvulso; }
            set { _idAvulso = value; }
        }

        public string Nome
        {
            get { return _nome; }
            set { _nome = value; }
        }
        public string CPF
        {
            get { return _cpf; }
            set { _cpf = value; }
        }

        public string TelefoneFixo
        {
            get { return _telefoneFixo; }
            set { _telefoneFixo = value; }
        }
        public string TelefoneCelular
        {
            get { return _telefoneCelular; }
            set { _telefoneCelular = value; }
        }
        public string Marca
        {
            get { return _marca; }
            set { _marca = value; }
        }
        public string Carro
        {
            get { return _carro; }
            set { _carro = value; }
        }
        public string Placa
        {
            get { return _placa; }
            set { _placa = value; }
        }
        public string Cor
        {
            get { return _cor; }
            set { _cor = value; }
        }
        [DataType(DataType.MultilineText)]
        public string Obs
        {
            get { return _obs; }
            set { _obs = value; }
        }

        public bool Persisted { get; set; }
        #endregion

        #region Construtores

        public Avulso()
        {
            Persisted = false;
        }

        public Avulso(int IdAvulso)
        {
            this._idAvulso = IdAvulso;
            Persisted = true;
        }
        #endregion
    }
}

ZTC/Controllers/AvulsoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ZTC.Bll;
using ZTC.Model;
using ZTC.Models;
using ZTC.Models.ENUMS;
using System.Net.Mail;

namespace ZTC.Controllers
{
    public class AvulsoController : BaseController
    {
        // GET: Avulso
        [AccessDeniedAuthorize]
        public ActionResult Index()
        {
            var avulso = new List<Avulso>();
            var bll = new AvulsoBll();

            string sql = "";

            avulso = bll.GetList(sql, true);

            return View(avulso);

        }

        // GET: Avulso/Details/5
        [AccessDeniedAuthorize]
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Avulso/Create
        [AccessDeniedAuthorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Avulso/Create
        [AccessDeniedAuthorize]
        [HttpPost]
        public ActionResult Create(Avulso avulso,FormCollection collection)
        {
            try
            {
                var bll = new AvulsoBll();

                bll.Save(avulso);


                Success("Sucesso", "Salvo com sucesso!", true);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Danger("Erro", string.Format("Erro: " + ex.Message), true);
                return View();
            }
        }

        // GET: Avulso/Edit/5
        [AccessDeniedAuthorize]
        public ActionResult Edit(int id)
        {
            var bll = new AvulsoBll();
            var avulso = bll.GetObject(id);




            if (avulso == null)
            {
                return HttpNotFound();
            }

            return View(avulso);
        }

        // POST: Avulso/Edit/5
        [AccessDeniedAuthorize]
        [HttpPost]
        public ActionResult Edit(Avulso avulso, FormCollection collection)
        {
            avulso.Nome = collection["Nome"];
            try
            {
                var bll = new AvulsoBll();
                bll.Save(avulso);
                Success("Sucesso", "Salvo com sucesso!", true);
                return RedirectToAction("/");
            }
            catch (Exception ex)
            {
                Danger("Erro", string.Format(ex.Message), true);
                return View(avulso);
            }
        }

        // GET: Avulso/Delete/5
        [AccessDeniedAuthorize]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Avulso/Delete/5
        [AccessDeniedAuthorize]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ZTC/Views/Avulso/Create.cshtml
@model ZTC.Model.Avulso

@{
    ViewBag.Title = "Criar Novo Mensalista";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    #tableUsuario tr td {
        padding: 5px 5px 5px 5px;
    }

    .drop-down {
        height: 20px;
    }

    .error {
        color: #a94442;
    }
</style>



<h2>Criar Novo Avulso</h2>
<div class="content">

    @using (Html.BeginForm("Create", "Avulso", FormMethod.Post, htmlAttributes: new { @id = "avulso" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <table class="CadPro">
            <tr>
                <td>Nome Avulso</td>
                <td>
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </td>
                <td width="92px">CPF</td>
                <td>
                    @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "input-pdr cpf", @style = "width:240px"} })
                    @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>Telefone Fixo</td>
                <td>
                    @Html.EditorFor(model => model.TelefoneFixo, new { htmlAttributes = new { @class = "input-pdr telefone", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.TelefoneFixo, "", new { @class = "text-danger" })
                </td>
                <td width="92px">Celular</td>
                <td>
                    @Html.EditorFor(model => model.TelefoneCelular, new { htmlAttributes = new { @class = "input-pdr telefone", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.TelefoneCelular, "", new { @class = "text-danger" })
                </td>
            </tr>

            <tr>
                <td>Dados do Carro</td>
                
            </tr>
            <tr>
                <td>Marca</td>
                <td>
                    @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
                </td>
                <td width="92px">Carro</td>
                <td>
                    @Html.EditorFor(model => model.Carro, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.Carro, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>Placa</td>
                <td>
                    @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })
                </td>
                <td width="92px">Cor</td>
                <td>
                    @Html.EditorFor(model => model.Cor, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.Cor, "", new { @class = "text-danger" })
                </td>
            </tr>
            
            <tr>
                <td>Obs</td>
                <td>
                    @Html.EditorFor(model => model.Obs, new { htmlAttributes = new { @class = "input-pdr", @style = "width:600px", @maxlength = "255" } })
                    @Html.ValidationMessageFor(model => model.Obs, "", new { @class = "text-danger" })
                </td>
            </tr>


                <tr>
                    <td colspan="4">
                        <input type="submit" value="Salvar" class="btn btnGreen" style="width: 85px; height: 34px; margin-left: 160px" />
                        <a href='@Url.Action("/", "Avulso")'>
                            <input type="button" class="btn btnWhite dropdown-toggle" style="width: 85px; height: 34px;" value="Cancelar" />
                        </a>
                    </td>
                </tr>
            </table>
        
       
    }

</div>

<script>

     $(function ($) {
         $("#Placa").mask("aaa-9999");
         

     });

</script>

ZTC/Views/Avulso/Edit.cshtml
@model ZTC.Model.Avulso

@{
    ViewBag.Title = "Edit";
}
<style>
    #tableUsuario tr td {
        padding: 5px 5px 5px 5px;
    }

    .error {
        color: #a94442;
    }

    .tablespc tr td {
        padding-right: 10px;
        padding-bottom: 5px;
        padding-top: 5px;
    }

    span.font {
        font-size: 24px;
        font-weight: 300;
        color: #333;
    }
</style>


<h2>Editar Avulso</h2>

<div class="content">

@using (Html.BeginForm("Edit", "Avulso", FormMethod.Post, htmlAttributes: new { @id = "avulso" }))
{
    @Html.AntiForgeryToken()
    
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdAvulso)   
    @Html.HiddenFor(model => model.Persisted)
    
    <table class="CadPro">
        <tr>
            <td>Nome Avulso</td>
            <td>
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </td>
            <td width="92px">CPF</td>
            <td>
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "input-pdr cpf", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>Telefone Fixo</td>
            <td>
                @Html.EditorFor(model => model.TelefoneFixo, new { htmlAttributes = new { @class = "input-pdr telefone", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.TelefoneFixo, "", new { @class = "text-danger" })
            </td>
            <td width="92px">Celular</td>
            <td>
                @Html.EditorFor(model => model.TelefoneCelular, new { htmlAttributes = new { @class = "input-pdr telefone", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.TelefoneCelular, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>Dados do Carro</td>

        </tr>
        <tr>
            <td>Marca</td>
            <td>
                @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
            </td>
            <td width="92px">Carro</td>
            <td>
                @Html.EditorFor(model => model.Carro, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.Carro, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>Placa</td>
            <td>
                @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })
            </td>
            <td width="92px">Cor</td>
            <td>
                @Html.EditorFor(model => model.Cor, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.Cor, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>Obs</td>
            <td>
                @Html.EditorFor(model => model.Obs, new { htmlAttributes = new { @class = "input-pdr", @style = "width:600px", @maxlength = "255" } })
                @Html.ValidationMessageFor(model => model.Obs, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <input type="submit" value="Salvar" class="btn btnGreen" style="width: 85px; height: 34px; margin-left: 160px" />
                <a href='@Url.Action("/", "Avulso")'>
                    <input type="button" class="btn btnWhite dropdown-toggle" style="width: 85px; height: 34px;" value="Cancelar" />
                </a>
            </td>
            
        </tr>
    </table>
}


</div>
<script>

     $(function ($) {
         $("#Placa").mask("aaa-9999");


     });

</script>

ZTC/Views/Avulso/Index.cshtml
@model List<ZTC.Model.Avulso>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Index";
}
<style>
    .table tr td, th {
        font-size: 11px;
    }

    .datetimepicker {
        z-index: 100000;
    }

    .espacamentoTd {
        padding: 3px;
    }

    .dropdown-new {
        font-size: 11px;
        max-height: 28px;
    }

    .bs-example {
        margin: 20px;
    }

    .icon-input-btn {
        display: inline-block;
        position: relative;
    }

        .icon-input-btn input[type="submit"] {
            padding-left: 2em;
        }

        .icon-input-btn .glyphicon {
            display: inline-block;
            position: absolute;
            left: 0.65em;
            top: 30%;
        }
</style>

<style>
    div.funil {
        width: 350px;
        /*height: 126px;
            border-top: 3px solid #c90000;
            background-color: #fff;
            box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.2);*/
    }

        div.funil input {
            width: 164px;
            /*margin: 6px 0 6px 6px;*/
        }

        div.funil hr {
            border: 0px;
            height: 1px;
            margin: 0px;
            background: #E5E5E5;
        }

        div.funil table {
            font-size: 11pt;
        }

        div.funil div.botDown {
            /*background: #f9e5e5;
                color: #c90000;
                border-top: 2px solid #c90000;*/
            height: 64px;
            font-size: 22pt;
            text-align: center;
            cursor: pointer;
        }

    .tableFiltro td.tdFiltro {
        /*padding: 10px;*/
    }

    div.overlay {
        z-index: 50;
        /*background: rgba(255,255,255,0.7);
            position: absolute;
            width: 350px;
            height: 126px;*/
    }

    div.funil .overlay > .fa, .overlay-wrapper .overlay > .fa {
        position: absolute;
        margin-left: 50px;
        /*margin-top: 52px;*/
        color: #000;
        font-size: 30px;
        z-index: 9999;
        opacity: 1;
    }

    .opacity-overlay {
        opacity: 0.3;
    }

    .fa-spin {
    }
</style>


<h2>Avulso</h2>




<div class="content" style="padding: 10px; width: 1120px">
    <input type="button" name="button" class="btn btnGreen" value="Adicionar Avulso" onclick='javascript: location.href = "@Url.Action("Create", "Avulso")"' />
    <br /><br />
    <table class="table table-striped">
        <tr>
            <th style="text-align:center">
                Nome
            </th>
            <th style="text-align:center">
                Telefone Fixo
            </th>
            <th style="text-align:center">
                Celular
            </th>
            <th style="text-align:center">
                Carro
            </th>
            <th style="text-align:center">
                Placa
            </th>
            <th style="text-align:center">
                Obs
            </th>
           <th style="text-align:center">Ações</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.TelefoneFixo)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.TelefoneCelular)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Carro)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Placa)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Obs)
                </td>
                <td style="text-align:center">
                        <a href="@Url.Action("Edit", "Avulso", new { id = item.IdAvulso })" class="btn btn-xs btn-pen tooltipicon" data-title="Editar"><span class="glyphicon glyphicon-pencil"></span></a>
            </tr>
        }
    </table>

</div>

<script>
    $(".tooltipicon").ggtooltip({ textcolor: "#FFF", backcolor: "#3C3C3C", bordercolor: "#3C3C3C", placement: "top" });
</script>