ZTC/Models/ServicoMensalista.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using ZTC.Models.ENUMS;

namespace ZTC.Model
{
    [Serializable]
    public class ServicoMensalista
    {
        #region Atributos
        private int _idServicoMensalista;
        private string _nome;
        private string _placa;
        private string _carro;
        private string _servico1;
        private string _observacao1;
        private string _servico2;
        private string _observacao2;
        private string _servico3;
        private string _observacao3;
        private DateTime? _dataHoraEntrada;
        private DateTime? _dataHoraSaida;
        private decimal _valorServico;
        private decimal _valorHora;
        private string _totalHoras;
        private decimal _valorTotal;
        private string _formaPagamento;
        private bool _fechado;
        #endregion

        #region Propriedades

        public int IdServicoMensalista
        {
            get { return _idServicoMensalista; }
            set { _idServicoMensalista = value; }
        }
        public string Nome
        {
            get { return _nome; }
            set { _nome = value; }
        }


        public string Placa
        {
            get { return _placa; }
            set { _placa = value; }
        }
        public string Carro
        {
            get { return _carro; }
            set { _carro = value; }
        }

        public string Servico1
        {
            get { return _servico1; }
            set { _servico1 = value; }
        }
        public string Observacao1
        {
            get { return _observacao1; }
            set { _observacao1 = value; }
        }
        public string Servico2
        {
            get { return _servico2; }
            set { _servico2 = value; }
        }
        public string Observacao2
        {
            get { return _observacao2; }
            set { _observacao2 = value; }
        }
        public string Servico3
        {
            get { return _servico3; }
            set { _servico3 = value; }
        }
        public string Observacao3
        {
            get { return _observacao3; }
            set { _observacao3 = value; }
        }
        public DateTime? DataHoraEntrada
        {
            get { return _dataHoraEntrada; }
            set { _dataHoraEntrada = value; }
        }
        public DateTime? DataHoraSaida
        {
            get { return _dataHoraSaida; }
            set { _dataHoraSaida = value; }
        }
        public decimal ValorServico
        {
            get { return _valorServico; }
            set { _valorServico = value; }
        }
        public decimal ValorHora
        {
            get { return _valorHora; }
            set { _valorHora = value; }
        }
        public string TotalHoras
        {
            get { return _totalHoras; }
            set { _totalHoras = value; }
        }
        public decimal ValorTotal
        {
            get { return _valorTotal; }
            set { _valorTotal = value; }
        }
        public string FormaPagamento
        {
            get { return _formaPagamento; }
            set { _formaPagamento = value; }
        }

        public bool Fechado
        {
            get { return _fechado; }
            set { _fechado = value; }
        }

        public bool Persisted { get; set; }
        #endregion

        #region Construtores

        public ServicoMensalista()
        {
            Persisted = false;
        }

        public ServicoMensalista(int IdServicoMensalista)
        {
            this._idServicoMensalista = IdServicoMensalista;
            Persisted = true;
        }
        #endregion
    }
}

ZTC/Controllers/ServicoMensalistaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ZTC.Bll;
using ZTC.Model;
using ZTC.Models;
using ZTC.Models.ENUMS;
using System.Net.Mail;
using System.IO;

namespace ZTC.Controllers
{
    public class ServicoMensalistaController : BaseController
    {
        // GET: Entrada
        [AccessDeniedAuthorize]
        public ActionResult Index()
        {
            var entrada = new List<ServicoMensalista>();
            var bll = new ServicoMensalistaBll();

            string sql = "";

            entrada = bll.GetList(sql, true);

            return View(entrada);
        }

        // GET: Entrada/Details/5
        [AccessDeniedAuthorize]
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Entrada/Create
        [AccessDeniedAuthorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Entrada/Create
        [AccessDeniedAuthorize]
        [HttpPost]
        public ActionResult Create(ServicoMensalista servicoMensalista, FormCollection collection)
        {
            try
            {
                var bll = new ServicoMensalistaBll();

                servicoMensalista.Placa = collection["placa"];
                servicoMensalista.Carro = collection["carro"];
                servicoMensalista.Nome = collection["nomeCliente"];
                //servicoMensalista.DataHoraEntrada = collection["dataLimiteRetorno"] != "" ? DateTime.Parse(collection["dataLimiteRetorno"]) : (DateTime?)null;
                servicoMensalista.DataHoraEntrada = collection["dataEntrada"] != "" ? DateTime.Parse(collection["dataEntrada"] + " " + collection["horaEntrada"]) : (DateTime?)null;
                //servicoMensalista.DataHoraEntrada = collection["dataEntrada"] != "" ? DateTime.Parse(collection["dataEntrada"]) + collection["horaEntrada"] != "" ? DateTime.Parse(collection["horaEntrada"]) : (DateTime?)null : (DateTime?)null;
                //servicoMensalista.DataHoraSaida = collection["dataSaida"] != "" ? DateTime.Parse(collection["dataSaida"]) + collection["horaSaida"] != "" ? DateTime.Parse(collection["horaSaida"]) : (DateTime?)null : (DateTime?)null;
                servicoMensalista.DataHoraSaida = collection["dataSaida"] != "" ? DateTime.Parse(collection["dataSaida"] + " " + collection["horaSaida"]) : (DateTime?)null;
                servicoMensalista.Servico1 = collection["servico1"];
                servicoMensalista.Servico2 = collection["servico2"];
                servicoMensalista.Servico3 = collection["servico3"];
                servicoMensalista.Observacao1 = collection["obs1"];
                servicoMensalista.Observacao2 = collection["obs2"];
                servicoMensalista.Observacao3 = collection["obs3"];

                servicoMensalista.ValorServico = Convert.ToDecimal(collection["valorServico"]);
                servicoMensalista.ValorHora = Convert.ToDecimal(collection["valorHora"]);
                servicoMensalista.TotalHoras = collection["totalHoras"];
                servicoMensalista.ValorTotal = Convert.ToDecimal(collection["valorTotal"]);
                servicoMensalista.FormaPagamento = collection["formaPagamento"];

                bll.Save(servicoMensalista);

                GetFileEntrada(servicoMensalista.IdServicoMensalista, servicoMensalista);

                Success("Sucesso", "Salvo com sucesso!", true);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Danger("Erro", string.Format("Erro: " + ex.Message), true);
                return View();
            }
        }

        // GET: Entrada/Edit/5
        [AccessDeniedAuthorize]
        public ActionResult Edit(int id)
        {
            var bll = new ServicoMensalistaBll();
            var servicoMensalista = bll.GetObject(id);

            
            if (servicoMensalista == null)
            {
                return HttpNotFound();
            }

            return View(servicoMensalista);
        }

        // POST: Entrada/Edit/5
        [AccessDeniedAuthorize]
        [HttpPost]
        public ActionResult Edit(ServicoMensalista servicoMensalista, FormCollection collection)
        {

            try
            {
                var bll = new ServicoMensalistaBll();

                servicoMensalista.Placa = collection["placa"];
                servicoMensalista.Carro = collection["carro"];
                servicoMensalista.Nome = collection["nome"];
                servicoMensalista.DataHoraEntrada = collection["dataHoraEntrada"] != "" ? DateTime.Parse(collection["dataHoraEntrada"] + " " + collection["horaEntrada"]) : (DateTime?)null;
                servicoMensalista.DataHoraSaida = collection["dataSaida"] != "" ? DateTime.Parse(collection["dataSaida"] + " " + collection["horaSaida"]) : (DateTime?)null;
                servicoMensalista.Servico1 = collection["servico1"];
                servicoMensalista.Servico2 = collection["servico2"];
                servicoMensalista.Servico3 = collection["servico3"];
                servicoMensalista.Observacao1 = collection["obs1"];
                servicoMensalista.Observacao2 = collection["obs2"];
                servicoMensalista.Observacao3 = collection["obs3"];

                servicoMensalista.ValorServico = Convert.ToDecimal(collection["valorServico"]);
                servicoMensalista.ValorHora = Convert.ToDecimal(collection["valorHora"]);
                servicoMensalista.TotalHoras = collection["totalHoras"];
                servicoMensalista.ValorTotal = Convert.ToDecimal(collection["valorTotal"]);
                servicoMensalista.FormaPagamento = collection["formaPagamento"];

                bll.Save(servicoMensalista);

                GetFileSaida(servicoMensalista.IdServicoMensalista, servicoMensalista);

                Success("Sucesso", "Salvo com sucesso!", true);
                return RedirectToAction("/");
            }
            catch (Exception ex)
            {
                Danger("Erro", string.Format(ex.Message), true);
                return View(servicoMensalista);
            }
        }

        // GET: Entrada/Delete/5
        [AccessDeniedAuthorize]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Entrada/Delete/5
        [AccessDeniedAuthorize]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public FileStreamResult GetFileEntrada(int id, ServicoMensalista servicoMensalista)
        {


            string name = @"D:\Teste\" + id + "_ENTRADA" + ".txt";

            FileInfo info = new FileInfo(name);
            if (!info.Exists)
            {
                using (StreamWriter writer = info.CreateText())
                {
                    writer.WriteLine("");
                    writer.WriteLine("ZTC PARKING");
                    writer.WriteLine("RUA DR.BEZERRA DE MENEZES, 113 - AHU");
                    writer.WriteLine("");
                    writer.WriteLine("ENTRADA - MENSALISTA");
                    writer.WriteLine("TICKET: " + id);
                    writer.WriteLine("DATA HORA ENTRADA: " + servicoMensalista.DataHoraEntrada);
                    writer.WriteLine("PLACA: " + servicoMensalista.Placa);
                    writer.WriteLine("CARRO: " + servicoMensalista.Carro);
                    writer.WriteLine("NOME: " + servicoMensalista.Nome);

                }
            }

            else
            {
                using (StreamWriter writer = info.CreateText())
                {
                    writer.WriteLine("");
                    writer.WriteLine("ZTC PARKING");
                    writer.WriteLine("RUA DR.BEZERRA DE MENEZES, 113 - AHU");
                    writer.WriteLine("");
                    writer.WriteLine("ENTRADA - MENSALISTA");
                    writer.WriteLine("TICKET: " + id);
                    writer.WriteLine("DATA HORA ENTRADA: " + servicoMensalista.DataHoraEntrada);
                    writer.WriteLine("PLACA: " + servicoMensalista.Placa);
                    writer.WriteLine("CARRO: " + servicoMensalista.Carro);
                    writer.WriteLine("NOME: " + servicoMensalista.Nome);

                }
            }

            return File(info.OpenRead(), "text/plain");

        }

        public FileStreamResult GetFileSaida(int id, ServicoMensalista servicoMensalista)
        {


            string name = @"D:\Teste\" + id + "_SAIDA" + ".txt";

            FileInfo info = new FileInfo(name);
            if (!info.Exists)
            {
                using (StreamWriter writer = info.CreateText())
                {
                    writer.WriteLine("");
                    writer.WriteLine("ZTC PARKING");
                    writer.WriteLine("RUA DR.BEZERRA DE MENEZES, 113 - AHU");
                    writer.WriteLine("");
                    writer.WriteLine("SAÍDA - MENSALISTA");
                    writer.WriteLine("TICKET: " + id);
                    writer.WriteLine("DATA HORA ENTRADA: " + servicoMensalista.DataHoraEntrada);
                    writer.WriteLine("DATA HORA SAÍDA: " + servicoMensalista.DataHoraSaida);
                    writer.WriteLine("PLACA: " + servicoMensalista.Placa);
                    writer.WriteLine("CARRO: " + servicoMensalista.Carro);
                    writer.WriteLine("NOME: " + servicoMensalista.Nome);

                }
            }

            else
            {
                using(StreamWriter writer = info.CreateText())
                {
                    writer.WriteLine("");

ZTC/Views/ServicoMensalista/Create.cshtml
@model ZTC.Model.ServicoMensalista

@{
    ViewBag.Title = "Criar Novo Mensalista";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #tableUsuario tr td {
        padding: 5px 5px 5px 5px;
    }

    .drop-down {
        height: 20px;
    }

    .error {
        color: #a94442;
    }
</style>


<script src="~/Scripts/jquery.worked-hours-grid.js"></script>
<script src="~/Scripts/jquery.worked-hours-grid.min.js"></script>
<h2>Criar Novo Serviço Mensalista</h2>
<div class="content">

    <form action="@Url.Action("Create", "ServicoMensalista")" method="POST" name="form1">
        <input type="hidden" name="idMensalista" id="idMensalista" />

        <table class="CadPro ts-grid">

            <tr>
                <td width="130px">
                    <span>Placa</span>
                </td>
                <td colspan="5">
                    <input type="text" name="placa" id="placa" class="input-pdr" style="width: 173px;" required="required" />
                    <button id="btnBuscarPorNomeEmpresa" class="btnPesquisar tooltipicon" data-title="Pesquisar"><span class="glyphicon glyphicon-search"></span></button>
                    <button type="button" name="limparCampos1" id="limparCampos1" value="Limpar" onclick="limparCampos()" title="Limpar Dados Empresa" alt="Limpar Dados Empresa" class="btn btn-sm btn-row glyphicon glyphicon-remove hide"></button>
                </td>
            </tr>
            <tr>
                <td>Carro</td>
                <td>
                    <input type="text" id="carro" name="carro" class="input-pdr" style="width: 173px" required="required" />
                </td>
                <td>Nome Cliente</td>
                <td>
                    <input type="text" id="nomeCliente" name="nomeCliente" class="input-pdr" style="width: 220px" />
                </td>


            </tr>

            <tr>
                <td>Data Entrada</td>
                <td colspan="1">
                    <input name="dataEntrada" id="dataEntrada" type="text" class="input-pdr datetimepicker" style="width: 110px" value="@DateTime.Now"/>
                    @*<input class="input-pdr timepicker_bottom text-box single-line" id="horaEntrada" maxlength="5" name="horaEntrada" style="width:60px" type="text">*@
                    @*<input class="input-pdr timepicker_bottom text-box single-line" id="horaEntrada" maxlength="5" name="horaEntrada" style="width:60px" type="text" value="@DateTime.Now.ToShortTimeString()">*@
                </td>
                <td>Data Saída</td>
                <td>
                    <input name="dataSaida" id="dataSaida" type="text" class="input-pdr datetimepicker" style="width: 110px" value="@DateTime.Now" />
                    @*<input class="input-pdr timepicker_bottom text-box single-line" id="horaSaida" maxlength="5" name="horaSaida" style="width:60px" type="text">*@
                    @*<input class="input-pdr timepicker_bottom text-box single-line" id="horaSaida" maxlength="5" name="horaSaida" style="width:60px" type="text" value="@DateTime.Now.ToShortTimeString()">*@
                </td>


            </tr>

            <tr class="ts-row">
                <td>Hora Entrada / Saída</td>
                @*<td class="ts-range">
                <input class="ts-time ts-start" type="time" value="10:00" /> to
                <input class="ts-time ts-end" type="time" value="12:00" />
            </td>*@

                <td class="ts-range">
                    <input class="ts-time ts-start" type="time" value="" id="horaEntrada" name="horaEntrada" /> -
                    <input class="ts-time ts-end" type="time" value="" id="horaSaida" name="horaSaida"/>
                </td>
                <td class="ts-sum" id="totalHoras" name="totalHoras" data-nome="totalHoras">
                    <input type="text" class="ts-time ts-sum" id="totalHoras" name="totalHoras" style="width: 173px" />
                </td>
            </tr>


            <tr>
                <td>Serviço 1:</td>
                <td style="position: relative;">
                    <select name="servico1" id="servico1" style="width: 170px">
                        <option>-</option>
                        <option name="servico1" value="Estacionamento">Estacionamento</option>
                        <option name="servico1" value="Lavagem">Lavagem</option>
                        <option name="servico1" value="Outros">Outros</option>
                    </select>
                </td>
                <td>Obs</td>
                <td>
                    <textarea type="text" id="obs1" name="obs1" class="input-pdr" style="width: 220px" cols="10" rows="2"></textarea>
                </td>

            </tr>

            <tr>
                <td>Serviço 2:</td>
                <td style="position: relative;">
                    <select name="servico2" id="servico" style="width: 170px">
                        <option>-</option>
                        <option name="servico2" value="Estacionamento">Estacionamento</option>
                        <option name="servico2" value="Lavagem">Lavagem</option>
                        <option name="servico2" value="Outros">Outros</option>
                    </select>
                </td>
                <td>Obs</td>
                <td>
                    <textarea type="text" id="obs2" name="obs2" class="input-pdr" style="width: 220px" cols="10" rows="2"></textarea>
                </td>

            </tr>

            <tr>
                <td>Serviço 3:</td>
                <td style="position: relative;">
                    <select name="servico3" id="servico3" style="width: 170px">
                        <option>-</option>
                        <option name="servico3" value="Estacionamento">Estacionamento</option>
                        <option name="servico3" value="Lavagem">Lavagem</option>
                        <option name="servico3" value="Outros">Outros</option>
                    </select>
                </td>
                <td>Obs</td>
                <td>
                    <textarea type="text" id="obs3" name="obs3" class="input-pdr" style="width: 220px" cols="10" rows="2"></textarea>
                </td>

            </tr>



            <tr>
                <td>Valor Serviço</td>
                <td>
                    <input type="text" id="valorServico" name="valorServico" class="input-pdr moeda" style="width: 173px" value="0,01"/>
                </td>
                <td>Valor Hora</td>
                <td>
                    <input type="text" id="valorHora" name="valorHora" class="input-pdr moeda" style="width: 220px" value="0,01"/>
                </td>


            </tr>

            <tr>
                @*<td>Total de Horas</td>
    <td>
        <input type="text" id="totalHoras" name="totalHoras" class="input-pdr" style="width: 173px" />
    </td>*@
                <td>Valor Total</td>
                <td>
                    <input type="text" id="valorTotal" name="valorTotal" class="input-pdr moeda" style="width: 220px" value="0,01"/>
                </td>


            </tr>
            



            <tr>
                <td>Forma de Pagamento</td>
                <td>
                    <input type="text" id="formaPagamento" name="formaPagamento" class="input-pdr" style="width: 173px" />
                </td>
                <td>Fechado:</td>
                <td width="166px">
                    @Html.EditorFor(model => model.Fechado)
                    @Html.ValidationMessageFor(model => model.Fechado, "", new { @class = "text-danger" })
                </td>


            </tr>

   

            <tr>
                <td colspan="6">
                    <input type="submit" value="Salvar" id="btnSalvar" class="btn btnGreen" style="width: 85px; height: 34px; margin-left: 130px;" />
                    <a href='@Url.Action("/", "ServicoMensalista")'>
                        <input type="button" class="btn btnWhite dropdown-toggle" value="Cancelar" style="width: 85px; height: 34px;" />
                    </a>
                </td>
            </tr>


        </table>
    </form>


</div>
<div id="popUpEmpresas" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content" style="width: 600px;">
            <div class="modal-header" style="border-bottom: 1px solid #ffffff;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div id="listEmpresas">

            </div>

        </div>

    </div>
</div>

<script>
    $(function ($) {
        $("#placa").mask("aaa-9999");
    });
</script>

<script type='text/javascript'>
	"use strict";
	$(function() {
      $(".ts-grid").workedHoursGrid({
        selectors: {
            	row: ".ts-row",
            	range: ".ts-range",
            	start: ".ts-start",
            	end: ".ts-end",
            	sum: ".ts-sum",
            	total: ".ts-total"
			}
      });
    });
</script>

<script>
    $("#btnBuscarPorNomeEmpresa").click(function () {
        CarregarEmpresaNomeEmpresa();
    });

    function CarregarEmpresaNomeEmpresa() {
        event.preventDefault();
        var item = $("#placa").val();


        $.ajax({
            url: "/api/ClientesApi/GetByNomeMensalista?placa=" + item,
            type: "GET",
            dataType: "JSON",
            success: function (arr) {
                var table = "";
                table += '<table class="table table-hover">';

                table += '<tr class="active">';
                table += '<td style="text-align: center;">Nome Cliente</td>';
                table += '<td style="text-align: center;">Carro</td>';
                table += '<td style="text-align: center;">Placa</td>';
                table += '<td style="text-align: center;">Selecione</td>';
                table += '</tr>';

                jQuery.each(arr, function (index, valor) {
                    //$("#placa").val(valor._placa);
                    //$("#nomeRepresentanteLegal").val(valor._idPessoaRepresentante._nome);
                    //$("#campocnpj").val(valor._cNPJ);
                    //console.log(valor);


                    table += '<tr>';
                    table += '<td style="text-align: center;">' + valor._nome + '</td>';
                    table += '<td style="text-align: center;">' + valor._carro + '</td>';
                    table += '<td style="text-align: center;">' + valor._placa + '</td>';
                    table += '<td style="text-align: center; cursor:pointer;"><a onclick="buscarCnpj(\'' + valor._nome + '\')">Selecionar</a></td>';
                    table += '</tr>';


                });
                table += "</table>";

                $("#listEmpresas").empty().append(table);

                $('#popUpEmpresas').modal('show');

                //if (valor._idEmpresa > 0);

                //else
                //    jAlert('Não existe empresas', 'Info');
            },
            error: function (valor) {
                $("#nomeRepresentanteLegal").val("");
                $("#campocnpj").val("");
                $("#fone").val("");
            }


        });


    }

    $("#btnBuscarPorCnpj").click(function () {
        CarregarEmpresaCnpj();
    });

    function buscarCnpj(nome) {
        $("#nomeCliente").val(nome);
        CarregarEmpresaCnpj();
        bloquearCampos();

        console.log(nome);
    }

    function CarregarEmpresaCnpj() {
        var item = $("#nomeCliente").val();


        $.ajax({
            url: "/api/ClientesApi/GetByNomeCliente?nomeCliente=" + item,
            type: "GET",
            dataType: "JSON",
            success: function (valor) {

                $("#placa").val(valor._placa);
                $("#carro").val(valor._carro);

                console.log(valor._nome);
                console.log(valor);
                if (valor._idMensalista > 0)
                    bloquearCampos();
                else
                    jAlert('PLACA não cadastrada', 'Info');
            },
            error: function (valor) {
                $("#placa").val("");
                $("#nomeCliente").val("");
            }
        });


    }

    function bloquearCampos(parameters) {
        $("#popUpEmpresas").modal("hide");
        $("#popUpRepresentante").modal("hide");
        $("#popUpCnpj").modal("hide");
        $("#nomeCliente").attr("disabled", false);
        $("#carro").attr("disabled", false);
        $("#placa").attr("disabled", false);
        $("#limparCampos1").removeClass("hide");
    }

    function limparCampos() {

        $("#limparCampos1").addClass("hide");
        document.getElementById('nomeCliente').value = "";
        document.getElementById('nomeCliente').disabled = false;
        document.getElementById('carro').value = "";
        document.getElementById('carro').disabled = false;
        document.getElementById('placa').value = "";
        document.getElementById('placa').disabled = false;
    }




</script>

ZTC/Views/ServicoMensalista/Index.cshtml
@model List<ZTC.Model.ServicoMensalista>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Index";
}
<style>
    .table tr td, th {
        font-size: 11px;
    }

    .datetimepicker {
        z-index: 100000;
    }

    .espacamentoTd {
        padding: 3px;
    }

    .dropdown-new {
        font-size: 11px;
        max-height: 28px;
    }

    .bs-example {
        margin: 20px;
    }

    .icon-input-btn {
        display: inline-block;
        position: relative;
    }

        .icon-input-btn input[type="submit"] {
            padding-left: 2em;
        }

        .icon-input-btn .glyphicon {
            display: inline-block;
            position: absolute;
            left: 0.65em;
            top: 30%;
        }
</style>

<style>
    div.funil {
        width: 350px;
        /*height: 126px;
            border-top: 3px solid #c90000;
            background-color: #fff;
            box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.2);*/
    }

        div.funil input {
            width: 164px;
            /*margin: 6px 0 6px 6px;*/
        }

        div.funil hr {
            border: 0px;
            height: 1px;
            margin: 0px;
            background: #E5E5E5;
        }

        div.funil table {
            font-size: 11pt;
        }

        div.funil div.botDown {
            /*background: #f9e5e5;
                color: #c90000;
                border-top: 2px solid #c90000;*/
            height: 64px;
            font-size: 22pt;
            text-align: center;
            cursor: pointer;
        }

    .tableFiltro td.tdFiltro {
        /*padding: 10px;*/
    }

    div.overlay {
        z-index: 50;
        /*background: rgba(255,255,255,0.7);
            position: absolute;
            width: 350px;
            height: 126px;*/
    }

    div.funil .overlay > .fa, .overlay-wrapper .overlay > .fa {
        position: absolute;
        margin-left: 50px;
        /*margin-top: 52px;*/
        color: #000;
        font-size: 30px;
        z-index: 9999;
        opacity: 1;
    }

    .opacity-overlay {
        opacity: 0.3;
    }

    .fa-spin {
    }
</style>


<h2>Serviço Mensalista</h2>




<div class="content" style="padding: 10px; width: 1120px">
    <input type="button" name="button" class="btn btnGreen" value="Adicionar Serviço Mensalista" onclick='javascript: location.href = "@Url.Action("Create", "ServicoMensalista")"' />
    <br /><br />
    <table class="table table-striped">
        <tr>
            <th style="text-align:center">
                Nome
            </th>
            <th style="text-align:center">
                Placa
            </th>
            <th style="text-align:center">
                Carro
            </th>
            <th style="text-align:center">
                Serviço 1
            </th>
            <th style="text-align:center">
                Data e Hora Entrada
            </th>
            <th style="text-align:center">
                Data e Hora Saída
            </th>
            <th style="text-align:center">
                Fechado
            </th>
           <th style="text-align:center">Ações</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Placa)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Carro)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Servico1)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.DataHoraEntrada)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.DataHoraSaida)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Fechado)
                </td>
                <td style="text-align:center">
                        <a href="@Url.Action("Edit", "ServicoMensalista", new { id = item.IdServicoMensalista })" class="btn btn-xs btn-pen tooltipicon" data-title="Editar"><span class="glyphicon glyphicon-pencil"></span></a>
            </tr>
        }
    </table>

</div>

<script>
    $(".tooltipicon").ggtooltip({ textcolor: "#FFF", backcolor: "#3C3C3C", bordercolor: "#3C3C3C", placement: "top" });
</script>