ZTC/Models/Mensalista.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using ZTC.Models.ENUMS;

namespace ZTC.Model
{
    [Serializable]
    public class Mensalista
    {
        #region Atributos
        private int _idMensalista;
        private string _nome;
        private string _cpf;
        private DateTime? _dataNascimento;
        private string _telefoneFixo;
        private string _telefoneCelular;
        private string _cep;
        private string _rua;
        private string _bairro;
        private string _cidade;
        private string _estado;
        private string _complemento;
        private string _marca;
        private string _carro;
        private string _placa;
        private string _cor;
        private decimal _valorMensal;
        private string _periodo;
        private string _vencimento;
        #endregion

        #region Propriedades

        public int IdMensalista
        {
            get { return _idMensalista; }
            set { _idMensalista = value; }
        }

        public string Nome
        {
            get { return _nome; }
            set { _nome = value; }
        }
        public string CPF
        {
            get { return _cpf; }
            set { _cpf = value; }
        }

        public DateTime? DataNascimento
        {
            get { return _dataNascimento; }
            set { _dataNascimento = value; }
        }
        public string TelefoneFixo
        {
            get { return _telefoneFixo; }
            set { _telefoneFixo = value; }
        }
        public string TelefoneCelular
        {
            get { return _telefoneCelular; }
            set { _telefoneCelular = value; }
        }
        public string CEP
        {
            get { return _cep; }
            set { _cep = value; }
        }
        public string Rua
        {
            get { return _rua; }
            set { _rua = value; }
        }
        public string Bairro
        {
            get { return _bairro; }
            set { _bairro = value; }
        }
        public string Cidade
        {
            get { return _cidade; }
            set { _cidade = value; }
        }
        public string Estado
        {
            get { return _estado; }
            set { _estado = value; }
        }
        public string Complemento
        {
            get { return _complemento; }
            set { _complemento = value; }
        }
        public string Marca
        {
            get { return _marca; }
            set { _marca = value; }
        }
        public string Carro
        {
            get { return _carro; }
            set { _carro = value; }
        }
        public string Placa
        {
            get { return _placa; }
            set { _placa = value; }
        }
        public string Cor
        {
            get { return _cor; }
            set { _cor = value; }
        }
        public decimal ValorMensal
        {
            get { return _valorMensal; }
            set { _valorMensal = value; }
        }
        public string Periodo
        {
            get { return _periodo; }
            set { _periodo = value; }
        }
        //public TimeSpan? Periodo
        //{
        //    get { return _periodo; }
        //    set { _periodo = value; }
        //}
        public string Vencimento
        {
            get { return _vencimento; }
            set { _vencimento = value; }
        }

        public bool Persisted { get; set; }
        #endregion

        #region Construtores

        public Mensalista()
        {
            Persisted = false;
        }

        public Mensalista(int IdMensalista)
        {
            this._idMensalista = IdMensalista;
            Persisted = true;
        }
        #endregion
    }
}

ZTC/Controllers/MensalistaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ZTC.Bll;
using ZTC.Model;
using ZTC.Models;
using ZTC.Models.ENUMS;
using System.Net.Mail;

namespace ZTC.Controllers
{
    public class MensalistaController : BaseController
    {
        // GET: Mensalista
        [AccessDeniedAuthorize]
        public ActionResult Index()
        {
            var mensalista = new List<Mensalista>();
            var bll = new MensalistaBll();

            string sql = "";

            //sql += " where MONTH(DataHoraSolicitacao) = MONTH(NOW()) and YEAR(DataHoraSolicitacao) = YEAR(NOW())  and TipoManutencao_Id = 2 ";
            mensalista = bll.GetList(sql, true);

            return View(mensalista);
        }

        // GET: Mensalista/Details/5
        [AccessDeniedAuthorize]
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Mensalista/Create
        [AccessDeniedAuthorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Mensalista/Create
        [AccessDeniedAuthorize]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Mensalista/Edit/5
        [AccessDeniedAuthorize]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Mensalista/Edit/5
        [AccessDeniedAuthorize]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Mensalista/Delete/5
        [AccessDeniedAuthorize]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Mensalista/Delete/5
        [AccessDeniedAuthorize]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ZTC/Views/Mensalista/Create.cshtml
@model ZTC.Model.Mensalista

@{
    ViewBag.Title = "Criar Novo Mensalista";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    #tableUsuario tr td {
        padding: 5px 5px 5px 5px;
    }

    .drop-down {
        height: 20px;
    }

    .error {
        color: #a94442;
    }
</style>

<script src="~/Content/jquery.searchabledropdown-1.0.8.src.js"></script>
@*<script src="//code.jquery.com/jquery-3.1.1.min.js"></script>*@
@*<script src="~/Content/jquery-3.1.1.min.js"></script>*@
<script type="text/javascript">

     function limpa_formulário_cep() {
         //Limpa valores do formulário de cep.
         document.getElementById('Rua').value = ("");
         document.getElementById('Bairro').value = ("");
         document.getElementById('Cidade').value = ("");
         document.getElementById('Estado').value = ("");
         //document.getElementById('ibge').value = ("");
     }

     function meu_callback(conteudo) {
         if (!("erro" in conteudo)) {
             //Atualiza os campos com os valores.
             document.getElementById('Rua').value = (conteudo.logradouro);
             document.getElementById('Bairro').value = (conteudo.bairro);
             document.getElementById('Cidade').value = (conteudo.localidade);
             document.getElementById('Estado').value = (conteudo.uf);
             //document.getElementById('ibge').value = (conteudo.ibge);
         } //end if.
         else {
             //CEP não Encontrado.
             limpa_formulário_cep();
             alert("CEP não encontrado.");
         }
     }

     function pesquisacep(valor) {

         //Nova variável "cep" somente com dígitos.
         var cep = valor.replace(/\D/g, '');

         //Verifica se campo cep possui valor informado.
         if (cep != "") {

             //Expressão regular para validar o CEP.
             var validacep = /^[0-9]{8}$/;

             //Valida o formato do CEP.
             if (validacep.test(cep)) {

                 //Preenche os campos com "..." enquanto consulta webservice.
                 document.getElementById('Rua').value = "...";
                 document.getElementById('Bairro').value = "...";
                 document.getElementById('Cidade').value = "...";
                 document.getElementById('Estado').value = "...";
                 //document.getElementById('ibge').value = "...";

                 //Cria um elemento javascript.
                 var script = document.createElement('script');

                 //Sincroniza com o callback.
                 script.src = '//viacep.com.br/ws/' + cep + '/json/?callback=meu_callback';

                 //Insere script no documento e carrega o conteúdo.
                 document.body.appendChild(script);

             } //end if.
             else {
                 //cep é inválido.
                 limpa_formulário_cep();
                 alert("Formato de CEP inválido.");
             }
         } //end if.
         else {
             //cep sem valor, limpa formulário.
             limpa_formulário_cep();
         }
     };

</script>


<h2>Criar Novo Mensalista</h2>
<div class="content">

    @using (Html.BeginForm("Create", "Mensalista", FormMethod.Post, htmlAttributes: new { @id = "mensalista" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <table class="CadPro">
            <tr>
                <td>Nome Mensalista</td>
                <td>
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "input-pdr", @style = "width:500px" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>CPF</td>
                <td>
                    @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "input-pdr cpf", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
                </td>
                <td width="92px">Data de Nascimento</td>
                <td>
                    @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "input-pdr datetimepicker", @style = "width:240px" , @maxlength = "10" } })
                    @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>Telefone Fixo</td>
                <td>
                    @Html.EditorFor(model => model.TelefoneFixo, new { htmlAttributes = new { @class = "input-pdr telefone", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.TelefoneFixo, "", new { @class = "text-danger" })
                </td>
                <td width="92px">Celular</td>
                <td>
                    @Html.EditorFor(model => model.TelefoneCelular, new { htmlAttributes = new { @class = "input-pdr telefone", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.TelefoneCelular, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>CEP</td>
                <td>
                    @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px", @maxlength = "8", @onblur = "pesquisacep(this.value);" } })
                    @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
                </td>
            </tr>


            <tr>
                <td>Rua</td>
                <td>
                    @Html.EditorFor(model => model.Rua, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.Rua, "", new { @class = "text-danger" })
                </td>
                <td width="92px">Bairro</td>
                <td>
                    @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
                </td>
            </tr>

            <tr>
                <td>Cidade</td>
                <td>
                    @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
                </td>
                <td width="92px">Estado</td>
                <td>
                    @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </td>
            </tr>

            <tr>
                <td>Complemento</td>
                <td>
                    @Html.EditorFor(model => model.Complemento, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
                </td>
            </tr>

            <tr>
                <td>Dados do Carro</td>
                
            </tr>
            <tr>
                <td>Marca</td>
                <td>
                    @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
                </td>
                <td width="92px">Carro</td>
                <td>
                    @Html.EditorFor(model => model.Carro, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.Carro, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>Placa</td>
                <td>
                    @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })
                </td>
                <td width="92px">Cor</td>
                <td>
                    @Html.EditorFor(model => model.Cor, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.Cor, "", new { @class = "text-danger" })
                </td>
            </tr>
            
            <tr>
                <td>R$</td>

            </tr>
            <tr>
                <td>Valor Mensal</td>
                <td>
                    @Html.EditorFor(model => model.ValorMensal, new { htmlAttributes = new { @class = "input-pdr moeda", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.ValorMensal, "", new { @class = "text-danger" })
                </td>
                <td width="92px">Período</td>
                <td>
                    @Html.EditorFor(model => model.Periodo, new { htmlAttributes = new { @class = "input-pdr hora", @style = "width:240px" } })
                    @Html.ValidationMessageFor(model => model.Periodo, "", new { @class = "text-danger" })
                </td>
            </tr>

            <tr>
                <td>Vencimento</td>
                <td>
                    @Html.EditorFor(model => model.Vencimento, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px", @maxlength = "2" } })
                    @Html.ValidationMessageFor(model => model.Vencimento, "", new { @class = "text-danger" })
                </td>
            </tr>








                <tr>
                    <td colspan="4">
                        <input type="submit" value="Salvar" class="btn btnGreen" style="width: 85px; height: 34px; margin-left: 160px" />
                        <a href='@Url.Action("/", "Mensalista")'>
                            <input type="button" class="btn btnWhite dropdown-toggle" style="width: 85px; height: 34px;" value="Cancelar" />
                        </a>
                    </td>
                </tr>
            </table>
        
       
    }

</div>

<script>

     $(function ($) {
         $("#Placa").mask("aaa-9999");
         

     });

</script>

ZTC/Views/Mensalista/Edit.cshtml
@model ZTC.Model.Mensalista

@{
    ViewBag.Title = "Edit";
}
<style>
    #tableUsuario tr td {
        padding: 5px 5px 5px 5px;
    }

    .error {
        color: #a94442;
    }

    .tablespc tr td {
        padding-right: 10px;
        padding-bottom: 5px;
        padding-top: 5px;
    }

    span.font {
        font-size: 24px;
        font-weight: 300;
        color: #333;
    }
</style>

<script src="~/Content/jquery.searchabledropdown-1.0.8.src.js"></script>
<script type="text/javascript">

    function limpa_formulário_cep() {
        //Limpa valores do formulário de cep.
        document.getElementById('Rua').value = ("");
        document.getElementById('Bairro').value = ("");
        document.getElementById('Cidade').value = ("");
        document.getElementById('Estado').value = ("");
        //document.getElementById('ibge').value = ("");
    }

    function meu_callback(conteudo) {
        if (!("erro" in conteudo)) {
            //Atualiza os campos com os valores.
            document.getElementById('Rua').value = (conteudo.logradouro);
            document.getElementById('Bairro').value = (conteudo.bairro);
            document.getElementById('Cidade').value = (conteudo.localidade);
            document.getElementById('Estado').value = (conteudo.uf);
            //document.getElementById('ibge').value = (conteudo.ibge);
        } //end if.
        else {
            //CEP não Encontrado.
            limpa_formulário_cep();
            alert("CEP não encontrado.");
        }
    }

    function pesquisacep(valor) {

        //Nova variável "cep" somente com dígitos.
        var cep = valor.replace(/\D/g, '');

        //Verifica se campo cep possui valor informado.
        if (cep != "") {

            //Expressão regular para validar o CEP.
            var validacep = /^[0-9]{8}$/;

            //Valida o formato do CEP.
            if (validacep.test(cep)) {

                //Preenche os campos com "..." enquanto consulta webservice.
                document.getElementById('Rua').value = "...";
                document.getElementById('Bairro').value = "...";
                document.getElementById('Cidade').value = "...";
                document.getElementById('Estado').value = "...";
                //document.getElementById('ibge').value = "...";

                //Cria um elemento javascript.
                var script = document.createElement('script');

                //Sincroniza com o callback.
                script.src = '//viacep.com.br/ws/' + cep + '/json/?callback=meu_callback';

                //Insere script no documento e carrega o conteúdo.
                document.body.appendChild(script);

            } //end if.
            else {
                //cep é inválido.
                limpa_formulário_cep();
                alert("Formato de CEP inválido.");
            }
        } //end if.
        else {
            //cep sem valor, limpa formulário.
            limpa_formulário_cep();
        }
    };

</script>




<h2>Editar Mensalista</h2>

<div class="content">

@using (Html.BeginForm("Edit", "Mensalista", FormMethod.Post, htmlAttributes: new { @id = "mensalista" }))
{
    @Html.AntiForgeryToken()
    
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdMensalista)   
    @Html.HiddenFor(model => model.Persisted)
    
    <table class="CadPro">
        <tr>
            <td>Nome Mensalista</td>
            <td>
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "input-pdr", @style = "width:500px" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>CPF</td>
            <td>
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "input-pdr cpf", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </td>
            <td width="92px">Data de Nascimento</td>
            <td>
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "input-pdr datetimepicker", @style = "width:240px", @maxlength = "10" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>Telefone Fixo</td>
            <td>
                @Html.EditorFor(model => model.TelefoneFixo, new { htmlAttributes = new { @class = "input-pdr telefone", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.TelefoneFixo, "", new { @class = "text-danger" })
            </td>
            <td width="92px">Celular</td>
            <td>
                @Html.EditorFor(model => model.TelefoneCelular, new { htmlAttributes = new { @class = "input-pdr telefone", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.TelefoneCelular, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>CEP</td>
            <td>
                @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px", @maxlength = "8", @onblur = "pesquisacep(this.value);" } })
                @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
            </td>
        </tr>


        <tr>
            <td>Rua</td>
            <td>
                @Html.EditorFor(model => model.Rua, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.Rua, "", new { @class = "text-danger" })
            </td>
            <td width="92px">Bairro</td>
            <td>
                @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>Cidade</td>
            <td>
                @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
            </td>
            <td width="92px">Estado</td>
            <td>
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>Complemento</td>
            <td>
                @Html.EditorFor(model => model.Complemento, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>Dados do Carro</td>

        </tr>
        <tr>
            <td>Marca</td>
            <td>
                @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
            </td>
            <td width="92px">Carro</td>
            <td>
                @Html.EditorFor(model => model.Carro, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.Carro, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>Placa</td>
            <td>
                @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })
            </td>
            <td width="92px">Cor</td>
            <td>
                @Html.EditorFor(model => model.Cor, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.Cor, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>R$</td>

        </tr>
        <tr>
            <td>Valor Mensal</td>
            <td>
                @Html.EditorFor(model => model.ValorMensal, new { htmlAttributes = new { @class = "input-pdr moeda", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.ValorMensal, "", new { @class = "text-danger" })
            </td>
            <td width="92px">Período</td>
            <td>
                @Html.EditorFor(model => model.Periodo, new { htmlAttributes = new { @class = "input-pdr hora", @style = "width:240px" } })
                @Html.ValidationMessageFor(model => model.Periodo, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>Vencimento</td>
            <td>
                @Html.EditorFor(model => model.Vencimento, new { htmlAttributes = new { @class = "input-pdr", @style = "width:240px", @maxlength = "2" } })
                @Html.ValidationMessageFor(model => model.Vencimento, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <input type="submit" value="Salvar" class="btn btnGreen" style="width: 85px; height: 34px; margin-left: 160px" />
                <a href='@Url.Action("/", "Mensalista")'>
                    <input type="button" class="btn btnWhite dropdown-toggle" style="width: 85px; height: 34px;" value="Cancelar" />
                </a>
            </td>
            
        </tr>
    </table>
}


</div>
<script>

    $(function ($) {
        $("#Placa").mask("aaa-9999");


    });

</script>